### PR TITLE
Add support for package.build.json.

### PR DESCRIPTION
**Pull request by borela**
This pull request makes postinstall checks the existence of a file `package.build.json` and if it exists, generate the command `npm install package@version...` for all packages listed there, if the file doesn't exist, it works as before. A use case can be seen [here](https://github.com/react-toolbox/react-toolbox/pull/992).

A flag `--cleanup` was added to allow deleting the node_modules dir and skip the prune command. This is also a fix for #11.

### CODE REVIEW

**Comment by exogen** [comment]
Thanks a ton for the PR, I realize I'm quite late in following up on it.

Here's what I'd like in order to support #11, as I [just commented there](https://github.com/exogen/postinstall-build/issues/11#issuecomment-288347870):

* I think a custom `package.json` field is a better approach rather than adding a new file. Plenty of precedent there and I'm fine with continuing that tradition.
* I'm not following you on the benefit of `--cleanup`, is the idea that it's faster than `prune`? Couldn't it potentially leave your install in a broken state? It kind of seems like a foot-gun to me, and I'd rather not encourage people to try and outsmart npm.
* When we construct the list of packages + versions to be installed, we'll need to be smarter than the `github` RegExp used here, as many more package sources can be specified (local folders, private git repos, BitBucket, and tons of other places). More likely we'll want to detect values that *do* look like versions instead of values that don't.

@borela If you're interested in making these (pretty major) adjustments, I'm happy to leave this PR open for updates. Otherwise, no worries, I can close this when I find some time to open a replacement PR. Thank you again! 😄

**Comment by borela** [comment]
I agree that having a custom field in `package.json` is a better approach, at the time of this pull request I was avoiding it but since then NPM is having no issues with custom fields and I constantly find myself adding babel, postcss, etc in there...

The idea of `--cleanup` was mostly for libraries where the dependencies were needed only for compilation and a parent project will already install them e.g. React Toolbox. But now that I look at it, the naming is a bit confusing.  In the React Toolbox's case, pruning or deleting the `node_modules` had the same effect but deleting was a lot faster.

I  won't be able to modify it for now as I am working some crazy hours on multiple projects these last months :c as soon as things calm down I'll make those changes.

**Comment by exogen** [comment]
Added support for `buildDependencies` in #20! 😃

**Comment by borela** [comment]
Thank you @exogen this feature will be extremely useful :D

**Pull request closed without merging**
